meta = ["type", "doc"]
edge_types = ["action", "trust"]

[nodes]
ORG_ADMIN.type = "role"
ORG_MANAGER.type = "role"
UNIT_MANAGER.type = "role"
COLL_ADMIN.type = "role"
RESEARCHER.type = "user"
CO_MEMBER.type = "role"

IDP.type = "entity"
IDP.doc = "embedded"
APPLICATION = "entity"
COLLABORATION = "entity"
ORGANISATION = "entity"
UNIT = "entity"
CO_GROUP = "entity"
APP_GROUP = "entity"

[plain_graph]
COLLABORATION.members = ["RESEARCHER_1", "RESEARCHER_2", "COLLABORATION_ADMIN"]
edges.entities = [["SURF", "ORGANISATION"], ["ORGANISATION", "COLLABORATION"]]
edges.entity_role = [["ORGANISATION", "ORG_ADMIN"], ["ORGANISATION", "ORG_MANAGER"]]
edges.actions = [["ORG_MANAGER", "COLLABORATION"], ["COLLABORATION_ADMIN", "RESEARCHER_1"], ["COLLABORATION_ADMIN", "RESEARCHER_2"]]
