meta = ["type", "doc"]
edge_types = ["action", "trust"]

[nodes_types]
ORG_ADMIN.type = "role"
ORG_MANAGER.type = "role"
UNIT_MANAGER.type = "role"
COLLABORATION_ADMIN.type = "role"
RESEARCHER.type = "user"
CO_MEMBER.type = "role"

IDP.type = "entity"
IDP.doc = "embedded"
APPLICATION.type = "service"
COLLABORATION.type = "entity"
ORGANISATION.type = "entity"
UNIT.type = "entity"
CO_GROUP.type = "group"
APP_GROUP.type = "group"

[plain_graph]
COLLABORATION.members = ["RESEARCHER_1", "RESEARCHER_2", "COLLABORATION_ADMIN"]
edges.entities = [["SURF", "ORGANISATION"], ["ORGANISATION", "COLLABORATION"]]
edges.entity_role = [["ORGANISATION", "ORG_ADMIN"], ["ORGANISATION", "ORG_MANAGER"]]
edges.actions = [["ORG_MANAGER", "COLLABORATION", "creates"], ["COLLABORATION_ADMIN", "RESEARCHER_1", "invites"], ["COLLABORATION_ADMIN", "RESEARCHER_2", "invites"]]
